# Generated by Django 3.0.5 on 2020-04-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('link', models.CharField(max_length=20)),
                ('exact', models.BooleanField(default=True)),
                ('icon', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('link', models.CharField(max_length=20)),
                ('exact', models.BooleanField(default=True)),
                ('icon', models.CharField(max_length=50)),
                ('contents', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='pages/contents_page/image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('link', models.CharField(max_length=20)),
                ('exact', models.BooleanField(default=True)),
                ('icon', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=20)),
                ('subheading', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('superscription', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pages/offer_page/offers')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('link', models.CharField(max_length=20)),
                ('exact', models.BooleanField(default=True)),
                ('icon', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('contents', models.CharField(max_length=2000)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('contact_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ContactPage')),
            ],
        ),
    ]
