# Generated by Django 3.0.5 on 2020-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background_image',
            field=models.ImageField(default='', upload_to='pages/home_page/background_image'),
            preserve_default=False,
        ),
    ]
