# Generated by Django 3.0.5 on 2020-05-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_configuration_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='favicon',
            field=models.ImageField(default='', upload_to='pages/configuration/icon', verbose_name='ikona ulubionych'),
        ),
    ]
