# Generated by Django 3.0.5 on 2020-06-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_configuration_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='language',
            field=models.CharField(choices=[('pl', 'polski'), ('en-us', 'angielski')], default='pl', max_length=20),
        ),
    ]
