# Generated by Django 3.0.5 on 2020-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homepage_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='pages/home_page/background_image'),
        ),
    ]
