# Generated by Django 3.0.5 on 2020-05-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_configuration_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, upload_to='pages/configuration/logo', verbose_name='logo'),
        ),
    ]
