# Generated by Django 3.0.5 on 2020-05-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_configuration_setup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'Konfiguracja', 'verbose_name_plural': 'Konfiguracja'},
        ),
    ]
