# Generated by Django 3.0.7 on 2020-06-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_configuration_setup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('pk',), 'verbose_name': 'Step', 'verbose_name_plural': 'Steps'},
        ),
    ]
