# Generated by Django 3.0.5 on 2020-05-27 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_configuration_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='wave_border_height',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
