# Generated by Django 3.0.5 on 2020-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_configuration_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='theme',
            field=models.CharField(choices=[('jasny', 'light'), ('ciemny', 'dark')], default='light', max_length=10),
        ),
    ]
