# Generated by Django 3.0.5 on 2020-05-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200513_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='theme',
            field=models.CharField(choices=[('light', 'jasny'), ('dark', 'ciemny')], default='light', max_length=10),
        ),
    ]
