# Generated by Django 3.0.7 on 2020-06-10 14:44

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200610_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='title',
            field=models.CharField(max_length=60, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='default_background_image',
            field=models.ImageField(blank=True, upload_to='pages/configuration/default_background_image', verbose_name='default background image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='default_background_size',
            field=models.CharField(choices=[('auto', 'auto'), ('cover', 'cover'), ('contain', 'contain')], default='cover', help_text='1vh = 1% viewport height.', max_length=20, verbose_name='default background size'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='favicon',
            field=models.ImageField(default='', upload_to='pages/configuration/icon', verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='language',
            field=models.CharField(choices=[('pl', 'polski'), ('en-us', 'english')], default='en-us', max_length=30, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, upload_to='pages/configuration/logo', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FF1744', max_length=18, verbose_name='primary color'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#ADD8E6', max_length=18, verbose_name='secondary color'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='site_name',
            field=models.CharField(default='Unknown', max_length=30, verbose_name='site name'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='theme',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=20, verbose_name='theme'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='wave_border_height',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='wave border height'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_form_email',
            field=models.EmailField(blank=True, help_text="If you don't want the contact form, leave it blank.", max_length=254, verbose_name='contact form email'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='contents',
            field=models.CharField(max_length=2000, unique=True, verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages/content_page/image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(max_length=50, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subheading',
            field=models.CharField(max_length=100, verbose_name='subheading'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='pages/offer_page/offers', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='superscription',
            field=models.CharField(blank=True, max_length=50, verbose_name='superscription'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='pages/page/background_image', verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='background_size',
            field=models.CharField(choices=[('auto', 'auto'), ('cover', 'cover'), ('contain', 'contain')], default='cover', max_length=20, verbose_name='background size'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='exact',
            field=models.BooleanField(default=True, verbose_name='exact'),
        ),
        migrations.AlterField(
            model_name='page',
            name='icon',
            field=models.CharField(max_length=50, unique=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.CharField(help_text="Leave '/' for the homepage, for the other pages start it with '/', for example '/contact'.", max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[/]([a-z0-9]?)+(?:-[a-z0-9]+)*$')], verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='contents',
            field=models.CharField(max_length=2000, unique=True, verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.CharField(max_length=500, unique=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='title'),
        ),
    ]
