# Generated by Django 3.0.5 on 2020-05-27 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_configuration_wave_border_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='wave_border_height',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Wysokość fali'),
        ),
    ]
