# Generated by Django 3.0.5 on 2020-05-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200513_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/home_page/background_image', verbose_name='tło'),
        ),
    ]
