# Generated by Django 3.0.5 on 2020-04-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contactpage_contact_form_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.SlugField(unique=True),
        ),
    ]
