# Generated by Django 3.0.7 on 2020-06-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200610_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'ordering': ('pk',), 'verbose_name': 'basic information', 'verbose_name_plural': 'basic informations'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'ordering': ('pk',), 'verbose_name': 'configuration', 'verbose_name_plural': 'configuration'},
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'ordering': ('pk',), 'verbose_name': 'contact page', 'verbose_name_plural': 'contact pages'},
        ),
        migrations.AlterModelOptions(
            name='contentpage',
            options={'ordering': ('pk',), 'verbose_name': 'content page', 'verbose_name_plural': 'content pages'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ('pk',), 'verbose_name': 'home page', 'verbose_name_plural': 'home pages'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('pk',), 'verbose_name': 'offer', 'verbose_name_plural': 'offers'},
        ),
        migrations.AlterModelOptions(
            name='offerpage',
            options={'ordering': ('pk',), 'verbose_name': 'offer page', 'verbose_name_plural': 'offer pages'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('pk',), 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('pk',), 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('pk',), 'verbose_name': 'step', 'verbose_name_plural': 'steps'},
        ),
    ]
