# Generated by Django 3.0.5 on 2020-04-29 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200428_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid link', regex='^[/][a-z0-9]+(?:-[a-z0-9]+)*$')]),
        ),
    ]
