# Generated by Django 3.0.5 on 2020-05-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200430_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages/content_page/image', verbose_name='obraz'),
        ),
    ]
