# Generated by Django 3.0.5 on 2020-05-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200521_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='theme',
            field=models.CharField(choices=[('light', 'jasny'), ('dark', 'ciemny')], default='light', max_length=10, verbose_name='motyw'),
        ),
    ]
