# Generated by Django 3.0.5 on 2020-05-02 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200502_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[/]([a-z0-9]?)+(?:-[a-z0-9]+)*$')]),
        ),
    ]
