# Generated by Django 3.0.5 on 2020-05-21 21:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200521_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FF1744', max_length=18, verbose_name='kolor podstawowy'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#ADD8E6', max_length=18, verbose_name='kolor pochodny'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='site_name',
            field=models.CharField(default='Unknown', max_length=30, verbose_name='nazwa strony'),
        ),
        migrations.AlterField(
            model_name='page',
            name='exact',
            field=models.BooleanField(default=True, verbose_name='nie posiada podstron'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=False, verbose_name='opublikowana'),
        ),
    ]
