# Generated by Django 3.0.5 on 2020-05-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200506_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='contact_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_infos', to='pages.ContactPage'),
        ),
    ]
