# Generated by Django 3.0.5 on 2020-05-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200521_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='background_image',
        ),
        migrations.AddField(
            model_name='page',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='pages/background_image', verbose_name='tło'),
        ),
    ]
