# Generated by Django 3.0.5 on 2020-05-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200506_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='ikona'),
        ),
    ]
