# Generated by Django 3.0.5 on 2020-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200522_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background_size',
            field=models.CharField(choices=[('auto', 'auto'), ('cover', 'pokrywaj'), ('zawieraj', 'contain')], default='auto', max_length=10, verbose_name='rozmiar tła'),
        ),
    ]
