# Generated by Django 3.0.5 on 2020-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200507_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='superscription',
            field=models.CharField(blank=True, max_length=50, verbose_name='nadtytuł'),
        ),
    ]
