# Generated by Django 3.0.5 on 2020-05-13 13:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20200508_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('theme', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], max_length=10)),
                ('primary_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('secondary_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
        ),
    ]
