# Generated by Django 3.0.5 on 2020-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_page_background_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='background_size',
            field=models.CharField(choices=[('auto', 'auto'), ('cover', 'pokrywaj'), ('contain', 'zawieraj')], default='auto', max_length=10, verbose_name='rozmiar tła'),
        ),
    ]
