# Generated by Django 3.0.5 on 2020-05-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200522_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='default_background_size',
            field=models.CharField(choices=[('auto', 'auto'), ('cover', 'pokrywaj'), ('contain', 'zawieraj')], default='cover', max_length=10, verbose_name='rozmiar domyślnego tła'),
        ),
    ]
