# Generated by Django 3.0.5 on 2020-05-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200513_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='company_name',
            field=models.CharField(max_length=30),
        ),
    ]
