# Generated by Django 3.0.5 on 2020-05-22 20:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_configuration_default_background_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#ADD8E6', max_length=18, verbose_name='kolor podstawowy'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#FF1744', max_length=18, verbose_name='kolor pochodny'),
        ),
    ]
